### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered for model "DockerImage".

### ISSUE THREAD

**Issue by rohanod** [rodyherrera/Quantum#1]
The title says it all but here is the full context:

```
(base) rohan@pi5:~ $ docker exec -it quantum-server npm run cli

> quantum-server@1.0.7 cli
> IS_CLI=true npx tsx cli/manager.ts

[13:17:50.630] INFO (461): @utilities/mongoConnector.ts (mongoConnector): Connecting to MongoDB (quantumcloud@production)...
[13:17:50.706] INFO (461): @utilities/mongoConnector.ts (mongoConnector): Connected to MongoDB (quantumcloud@production).
✔ Select an option to continue... › Create a new quantum user.
✔ Username … *****
✔ Your fullname … ******
✔ Email address … *******
✔ Password … *************
✔ Confirm password … *************
✔ Role › Admin
/app/node_modules/mongoose/lib/mongoose.js:573
      throw new _mongoose.Error.MissingSchemaError(name);
            ^

MissingSchemaError: Schema hasn't been registered for model "DockerImage".
Use mongoose.model(name, schema)
    at Mongoose.model (/app/node_modules/mongoose/lib/mongoose.js:573:13)
    at createUserContainer (/app/models/user.ts:131:34)
    at model.<anonymous> (/app/models/user.ts:194:36)

Node.js v20.11.0
```

By the way, I did not enter *** for all details; I'm just censoring it out.

**Comment by rodyherrera** [comment]
Hello!
You can try cloning the repository again. The errors were solved, since at the time of creating the user the models to which references were made were not being imported (this only in the CLI). I haven't released the current version yet, and I appreciate that you brought this to my attention.

I will be attaching a screenshot of how I created a user correctly.
![Screenshot from 2025-01-02 18-33-34](https://github.com/user-attachments/assets/b76bd29e-5374-4612-b5af-1cdedc8847d6)

Greetings!
